name: Kong on AWS with Terraform
categories:
  - deployment
publisher: Kong Inc.
type: integration
desc: Terraform module to provision Kong and Kong Gateway clusters on Amazon Web Services.
description: |
  Terraform module to provision Kong clusters in Amazon Web Service (AWS) using AWS best practices for architecture and security. Both Kong and Kong Gateway are supported. Available under the Apache License 2.0 license.
support_url: 'https://github.com/Kong/kong-terraform-aws/issues'
source_code: 'https://github.com/kong/kong-terraform-aws'
license_type: Apache-2.0
kong_version_compatibility:
  community_edition:
    compatible: true
  enterprise_edition:
    compatible: true
