name: SignalFx
api_id: true
service_id: true
consumer_id: true
route_id: true
dbless_compatible: yes
config:
  - name: aggregate_by_http_method
    required: yes
    default: true
    value_in_examples:
    description: |
      By default, metrics for each Service/API-fielded request cycle will be aggregated by a context determined partially by the request's HTTP method and by its response's status code.
      If you are monitoring a large infrastructure with hundreds of routes, grouping by HTTP method can be too granular or costly for performant `/signalfx` requests on a 1s interval, depending on the server resources.
      This context grouping can be disabled with the boolean configuration option `aggregate_by_http_method`.
name: SignalFx
publisher: SignalFx

categories: analytics-monitoring

desc: Monitor and analyze Kong in SignalFx
description: |
  This Kong plugin is intended for SignalFx users to obtain performance metrics from their Kong deployments for aggregation and reporting via the [Smart Agent](https://github.com/signalfx/signalfx-agent){:target="_blank"}{:rel="noopener noreferrer"} or the [collectd-kong](https://github.com/signalfx/collectd-kong){:target="_blank"}{:rel="noopener noreferrer"} collectd plugin. It works similarly to other Kong logging plugins and provides connection state and request/response count, latency, status, and size metrics available through a `/signalfx` Admin API endpoint.

support_url: https://support.signalfx.com/hc/en-us

source_code: https://github.com/signalfx/kong-plugin-signalfx

license_type: Apache-2.0

license_url: https://github.com/signalfx/kong-plugin-signalfx/blob/master/LICENSE

privacy_policy_url: https://signalfx.com/privacy-policy/

terms_of_service_url: https://signalfx.com/terms-and-conditions/

kong_version_compatibility:
  community_edition:
    compatible:
      - 0.12.x
      - 0.13.x
      - 0.14.x
    incompatible:
  enterprise_edition:
    compatible:
      - 0.32-x
      - 0.33-x
      - 0.34-x
    incompatible:

