name: kong-jwt2header
api_id: false
  # boolean - whether this plugin can be applied to an API [[this needs more]]
service_id: false
  # boolean - whether this plugin can be applied to a Service.
  # Affects generation of examples and config table.
consumer_id: false
  # boolean - whether this plugin can be applied to a Consumer.
  # Affects generation of examples and config table.
route_id: false
  # whether this plugin can be applied to a Route.
  # Affects generation of examples and config table.
protocols:
  - name: http
  - name: https
  # List of protocols this plugin is compatible with.
  # Valid values: "http", "https", "tcp", "tls"
  # Example: ["http", "https"]
dbless_compatible: 'yes'
  # Degree of compatibility with DB-less mode. Three values allowed:
  # 'yes', 'no' or 'partially'
dbless_explanation: Fully compatible with DB and DB-less (K8s, Declarative) Kong implementations.
  # Optional free-text explanation, usually containing details about the degree of
  # compatibility with DB-less.

config:
  - name: strip_claims
    required: yes
    default: "`false`"
    value_in_examples: false
    description: If enabled, claims will be removed from headers before being sent to the upstream. By default, each claim is passed upstream in a header prefixed with `X-Kong-JWT-Claim`.
  - name: token_required
    required: yes
    default: "`true`"
    value_in_examples: true
    description: By default, `token_required` is set to `true`, and an error will be returned if a valid JWT is not present in the request. Set it to `false` if you want this plugin to fail open and proceed with executing the request, regardless of whether a valid JWT is present or not.
