name: apig-request-transformer
api_id: false
service_id: true
consumer_id: false
route_id: true
protocols:
  - name: http
  - name: https
dbless_compatible: yes
dbless_explanation: It is recommended to use in dbless mode.
config:
  - name: httpMethod
    required: true
    default:
    value_in_examples: POST
    description: Changes the HTTP method for the upstream request.
  - name: backendContentType
    required: false
    default:
    value_in_examples: application/json
    description: Changes Content-Type for the upstream request.
  - name: requestPath
    required: false
    default:
    value_in_examples: /requestPath/[pageId]/[userId]
    description: It is used with [config.pathParams] to extract values from the request URI.
  - name: backendPath
    required: false
    default:
    value_in_examples: /servicePath/[pageId]/[userId]
    description: Updates the the path part of the upstream request URI with values.
  - name: pathParams
    required: semi
    default:
    value_in_examples: ["pageId", "userId"]
    description: List of parameters' names of the request URI.
  - name: replace
    required: false
    default:
    value_in_examples: ["head:h1;query:param1", "path:pageId;query:param2"]
    description: List of parameter mappings. Replace its old value with the new one at different locations.
  - name: add
    required: false
    default:
    value_in_examples: ["head:h1:v1", "query:param1:value1"]
    description: List of constant parameters. Set a new header or a new querystring with the given value.
extra:
  # This is for additional remarks about your configuration.
