name: Upstream HTTP Basic Authentication
api_id: true
service_id: true
consumer_id: false
route_id: true
dbless_compatible: yes
config:
  - name: username
    required: true
    value_in_examples: kingkong
    urlencode_in_examples:
    default:
    description: The username to send in the Authorization header to the upstream service
  - name: password
    required: true
    value_in_examples: 1-big-ape
    urlencode_in_examples:
    default:
    description: The password to send in the Authorization header to the upstream service
publisher: Revolution Systems Inc.

categories:
  - authentication

desc: Add HTTP Basic Authentication header to upstream service request

description: |
  Kong Plugin to add HTTP Basic Authentication to the upstream request header.

support_url: https://github.com/revolsys/kong-plugin-upstream-auth-basic/issues

source_code: https://github.com/revolsys/kong-plugin-upstream-auth-basic

license_type: Apache-2.0

kong_version_compatibility: # required
  community_edition: # optional
    compatible:
      - 0.14.x
      - 0.13.x
      - 0.12.x
    #incompatible:
  enterprise_edition: # optional
    compatible:
      - 0.34-x
      - 0.33-x
      - 0.32-x
      - 0.31-x
      - 0.30-x
    #incompatible:
