name: upstream-auth-basic
api_id: true
service_id: true
consumer_id: false
route_id: true
dbless_compatible: yes
config:
  - name: username
    required: true
    value_in_examples: kingkong
    urlencode_in_examples:
    default:
    description: The username to send in the Authorization header to the upstream service
  - name: password
    required: true
    value_in_examples: 1-big-ape
    urlencode_in_examples:
    default:
    description: The password to send in the Authorization header to the upstream service
